apiVersion: apps/v1
kind: Deployment
metadata:
  name: rights-app-website-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: rights-app-website
          image: europeana/rights-app-website
          ports:
            - containerPort: 4000
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health/liveness
#              httpHeaders:
#                - name: Accept
#                  value: application/json
#            initialDelaySeconds: 90
#            periodSeconds: 60
#          readinessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health/readiness
#              httpHeaders:
#                - name: Accept
#                  value: application/json
#            initialDelaySeconds: 60
#            periodSeconds: 60
