name: CI build
on: push
jobs:
  ci:
    name: Run continuous integration build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Ruby runtime
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Configure bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build the site 
        run: bundle exec jekyll build
